languages = [{
	lang: "Español",
	showAll: "Mostrar todos",
	textFilter: "Filtro textual",
	numericFilter: "Filtro numerico",
	graph: "Grafico",
	other: "Otro",
	accept: "Aceptar",
	activefilters: "Filtros activos",
	addSgvizlerWidget: "Crea un gráfico",
	addWidget: "Añade un Widget",
	addWidget2: "Añadir",
	advancedoptions: "Opciones avanzadas",
	alreadyAdded: "Ya añadido",
	autocomplete: "Autocompletar búsqueda con",
	barchart: "Gráfico de barras",
	barchartexp: "Representa el campo deseado en un gráfico de barras",
	closeconf: "Cerrar Configuración",
	configuration: "Configuración",
	corecaption: "Selecciona un Core",
	dashboard: 'Panel de Control',
	deleteAllFilters: "Borrar todos los filtros",
	demo1a: "Demo: Universidades europeas",
	demo1b: "Nivel: básico",
	demo1c: "Explora todas las posibilidades que SEFARAD de ofrece",
	demo1d: "Widgets totalmente configurables",
	demo1e: "Internamente, se realiza una consulta sparql a la dbpedia",
	demo1f: "Ver demo",
	demo2a: "Visita el repositorio del proyecto",
	demo2c: "En él, podrás encontrar toda la información que necesitas",
	demo2d: "Puedes clonar el proyecto a tu ordenador",
	demo2e: "GitHub",
	demo3a: "Sefarad Personalizado",
	demo3b: "Descárgate tu propio Sefarad",
	demo3c: "Selecciona los widgets que necesitas",
	demo3d: "También puedes descargar una versión completa",
	demo3e: "Ideal para no descargar aquello que no necesitas!",
	demo3f: "Descargar Sefarad",
	errorcore: "Se ha producido un error",
	errorcore1: "Ese Core no existe",
	errorcore2: "Debes especificar un Core",
	errorroute: "Ruta incorrecta",
	errorroute1: "Rutas válidas:",
	errorserverurl: "Se ha producido un error",
	errorserverurl1: "Debes especificar la URL del servidor",
	faq1a: "1. Instala LMF",
	faq1b: "LMF es un Framework que permite la configuración de un servidor avanzado, dando soporte a diferentes tecnologías Semánticas.",
	faq1c: "Dirígete a la Web oficial de LMF y descarga e instala LMF.",
	faq2a: "2. Importa tus datos",
	faq2b: "Introduce tus datos semánticos en la Base de Datos de LMF.",
	faq3a: "3. Haz consultas SPARQL",
	faq3b: "Una vez importados con éxito, ya puedes hacer consultas SPARQL desde SEFARAD.",
	faq3c: "",
	faq3d: "Si las consultas SPARQL resultan pesadas y quieres manejar grandes cantidades de datos, utiliza el siguiente módulo.",
	faq4a: "4. Configura un Core",
	faq4b: "Indexa los parámetros que quieras haciendo uso del lenguaje LDPath: http://code.google.com/p/ldpath/",
	faq4c: "",
	faq5a: "5. Usa SEFARAD",
	faq5b: "Dirígete a la siguiente ruta: sefarad.html#/main",
	faq5c: "¡Disfruta de la visualización!",
	fieldcaption: "Selecciona un campo",
	gauge: "Gauge",
	gaugeexp: "Visualiza el número de resultados",
	globalvar: "Variables globales",
	langcaption: "Selecciona un idioma",
	language: "Idioma",
	latitude: "Latitud:",
	lmfroute: "Ruta LMF",
	logo: "Logo de la página",
	longitude: "Longitud:",
	map: "Mapa",
	mapexp: "Si tus datos contienen coordenadas geográficas podrás representarlo en un mapa gracias a Google Maps.",
	mongodb: "Usar MongoDB",
	next: "Siguiente",
	nodata: "No hay datos",
	notActiveFilters: "No hay filtros activos",
	numericwidget: "Filtro numérico",
	numericwidgetexp: "Con este filtro, podrás restringir tu búsqueda mediante el establecimiento de un rango numérico para la propiedad deseada.",
	openconf: "Abrir Configuración",
	pagetitle: "Título de la página",
	panelbar: "Lista de Etiquetas (vertical)",
	panelbarexp: "Lista todos los valores según el campo deseado y aplica filtros individuales o múltiples.",
	perPage: "Por página",
	personalization: "Personalización",
	piechart: "Gráfico tipo tarta",
	piechartexp: "Representa el campo deseado en un gráfico tipo tarta",
	promoheader: "Descubre todas las posibilidades",
	reindexsolr: "Reindexar Core",
	resetconf: "Resetear la configuración",
	results: "Resultados",
	resultsgrid: "Resultados (grid)",
	resultsgridexp: "",
	resultstats: "Estadísticas de los Resultados",
	resultstatsexp: "Proporción",
	resultsvertical: "Resultados (vertical)",
	resultsverticalexp: "",
	savechanges: "Guardar cambios",
	search: 'Buscador',
	searchplaceholder: 'Introduce tu búsqueda aquí',
	sgvizler: "Estadísticas",
	sgvizlerexp: "Crea gráficos con consultas SPARQL",
	showingresults: 'Viendo resultados ',
	showMap: "Mostrar Mapa",
	showTwitter: "Mostrar Twitter",
	sortableWidgets: "Widgets ordenables",
	sparqlaccessendpoint: "Punto de acceso SPARQL",
	staticgraph: "Gráfico estático",
	staticgraphexp: "Gracias a la librería <a href='http://code.google.com/p/sgvizler/' target='_blank'>sgvizler</a> puedes realizar consultas SPARQL y que su respuesta se represente en un gráfico de manera casi mágica.",
	tagcloud: "Lista de Etiquetas",
	tagcloudexp: "Lista todos los valores según el campo deseado y aplica filtros individuales o múltiples.",
	tagcloudexp2: "¡Explorar tus datos nunca ha sido tan fácil!",
	tuto1: "SEFARAD offers you a lot of possibilities. Follow this little tour to take full advantage of the tool.",
	tuto2: "Desde este desplegable podrás personalizar la página: título, logo, hoja de estilo... Además de otros parámetros útiles como el autocompletado de la barra de búsqueda.",
	tuto3: "El widget más importante es completamente personalizable. ¡Elige qué campos son los que quieres visualizar en todo momento!",
	tuto4: "Añade gráficos personalizables, widgets para poder filtrar los campos que tú quieras, un mapa o el magnífico plugin de Twitter.",
	tuto5: "Realiza todas las búsquedas textuales que quieras. Disfruta del autocompletado y, si eres un usuario experto, prueba con consultas SPARQL.",
	tuto6: "Cuando realices cambios en los Widgets o en la configuración, ¡no te olvides de guardarlos!",
	tuto7: "Este proyecto se ha realizado en el GSI (Grupo de Sistemas Inteligentes) de la UPM (Universidad Politécnica de Madrid)",
	tutoh1: "¡Bienvenido!",
	tutoh2: "Configuración",
	tutoh3: "Tus resultados personalizados",
	tutoh4: "Más y más widgets",
	tutoh5: "Búsqueda textual",
	tutoh6: "¡Y guarda los cambios!",
	tutoh7: "Créditos",
	twitter: "Twitter",
	twitterexp: "Descubre lo qué se está hablando en Twitter sobre el campo de tus datos que tu elijas. Aprovecha las redes sociales para sacar más partido si cabe a tus datos.",
	widgetAAname: "widgetAA",
}, {
	lang: "English",
	showAll: "Show all",
	textFilter: "Textual filter",
	numericFilter: "Numeric filter",
	graph: "Graph",
	other: "Other",
	accept: "Accept",
	activefilters: "Active filters",
	addSgvizlerWidget: "Create new graph",
	addWidget: "Add a Widget",
	addWidget2: "Add",
	advancedoptions: "Advanced options",
	autocomplete: "Autocomplete search with",
	barchart: "Bar chart",
	barchartexp: "Shows the desired field into a bar chart	",
	closeconf: "Close Configuration",
	configuration: "Configuration",
	corecaption: "Choose a Core",
	dashboard: 'Dashboard',
	demo1a: "Demo: European universities",
	demo1b: "Level: basic",
	demo1c: "Learn all possibilities SEFARAD provides you",
	demo1d: "Customizable Widgets",
	demo1e: "It works with a sparql query to dbpedia",
	demo1f: "Go to demo",
	demo2a: "Visit the project repo",
	demo2c: "In our git repository you may find all the information you need",
	demo2d: "You can clone the project to your own computer",
	demo2e: "GitHub",
	demo3a: "Custom Sefarad",
	demo3b: "Download your own Sefarad",
	demo3c: "Select the widgets you need",
	demo3d: "You also can download a complete version",
	demo3e: "Ideal option for not downloading things that you don't need!",
	demo3f: "Download Sefarad",
	errorcore: "Ops! There was an error",
	errorcore1: "That Core doesn't exist",
	errorcore2: "You must specify one Core",
	errorroute: "Wrong route",
	errorroute1: "Valid routes:",
	errorserverurl: "Ops! There was an error",
	errorserverurl1: "You must setup server URL",
	faq1a: "Test",
	fieldcaption: "Choose a field",
	gauge: "Gauge",
	globalvar: "Global variables",
	langcaption: "Choose a language",
	language: "Language",
	latitude: "Latitude:",
	lmfroute: "LMF route",
	logo: "Page logo",
	longitude: "Longitude:",
	map: "Map",
	mapexp: "If you have geographic coordinates in your data, you can visualize them in a Map thanks to Google Maps.",
	mongodb: "Use MongoDB",
	next: "Next",
	nodata: "There is no data to show",
	numericwidget: "Numeric filter",
	numericwidgetexp: "Use this as a range slider so you can also filter fields with numbers.",
	openconf: "Open Configuration",
	pagetitle: "Page title",
	panelbar: "Tags (vertical)",
	panelbarexp: "Shows all values ​​about the desired field and applies single or multiple filters.",
	perPage: "Per page",
	personalization: "Personalization",
	piechart: "Piechart",
	piechartexp: "Shows the desired field into a piechart graph",
	promoheader: "Discover all possibilities",
	reindexsolr: "Reindex Core",
	resetconf: "Reset Configuration",
	results: "Results",
	resultsgrid: "Results (grid)",
	resultsgridexp: "",
	resultstats: "Results statistics",
	resultstatsexp: "Proportion",
	resultsvertical: "Results (vertical)",
	resultsverticalexp: "",
	savechanges: "Save changes",
	search: 'Search',
	searchplaceholder: 'Introduce your search here',
	sgvizler: "Statistics",
	sgvizlerexp: "Create graphs making SPARQL Queries",
	showingresults: 'Showing Results ',
	showMap: "Show Map",
	showTwitter: "Show Twitter Widget",
	sortableWidgets: "Sortable widgets",
	sparqlaccessendpoint: "SPARQL endpoint",
	staticgraph: "Static graph",
	staticgraphexp: "Thanks to <a href='http://code.google.com/p/sgvizler/' target='_blank'>sgvizler</a> library, you can make SPARQL queries and visualize the result in a pie chart.",
	tagcloud: "Tagcloud",
	tagcloudexp: "List all values of one certain field and apply all filters you want.",
	tagcloudexp2: "It's really easy to explore your data!",
	tuto1: "SEFARAD offers you many possibilities. Sit back and follow this small tour to get the most out of the tool.",
	tuto2: "From this drop-down page you can customize all the page configuration and other useful parameters such as sortable/no sortable widgets, autocomplete field, etc.",
	tuto3: "The most important widget! It's completely customizable. You can choose which fields you want to display.",
	tuto4: "Add customizable graphs, widgets to filter the fields that you want, a map or the amazing Twitter plugin.",
	tuto5: "Performs all textual searches you like. Enjoy the autocomplete and if you are an expert user, try SPARQL queries.",
	tuto6: "When you make your own changes to widgets or configuration, do not forget to save!",
	tuto7: "This project was carried out at GSI (Intelligent Systems Group, UPM)",
	tutoh1: "Welcome!",
	tutoh2: "Configuration",
	tutoh3: "Your custom results",
	tutoh4: "More and more widgets",
	tutoh5: "Textual search",
	tutoh6: "¡Save your changes!",
	tutoh7: "Credits",
	twitter: "Twitter",
	twitterexp: "Select a field and see what's going on Twitter about items contained in it.",
}, ];


