languages =
    [
        {
            lang: "Español",
		results: "Resultados",
		configuration: "Configuración",
		personalization: "Personalización",
		pagetitle: "Título de la página",
		logo: "Logo de la página",
                language: "Idioma",
		langcaption: "Selecciona un idioma",
                autocomplete: "Autocompletar búsqueda con",
		fieldcaption: "Selecciona un campo",
		globalvar: "Variables globales",
		lmfroute: "Ruta LMF",
		sparqlaccessendpoint: "Punto de acceso SPARQL",
                advancedoptions: "Opciones avanzadas",
                reindexsolr: "Reindexar Core",
                resetconf: "Resetear la configuración",
                savechanges: "Guardar cambios",
		openconf: "Abrir Configuración",
		closeconf: "Cerrar Configuración",
		addWidget: "Añade un Widget",
		addWidget2: "Añadir",
		tagcloud: "Lista de Etiquetas",
		tagcloudexp: "Lista todos los valores según el campo deseado y aplica filtros individuales o múltiples.",
		tagcloudexp2: "¡Explorar tus datos nunca ha sido tan fácil!",
		numericwidget: "Filtro numérico",
		numericwidgetexp: "Con este filtro, podrás restringir tu búsqueda mediante el establecimiento de un rango numérico para la propiedad deseada.",
		staticgraph: "Gráfico estático",
		staticgraphexp: "Gracias a la librería <a href='http://code.google.com/p/sgvizler/' target='_blank'>sgvizler</a> puedes realizar consultas SPARQL y que su respuesta se represente en un gráfico de manera casi mágica.",
		map: "Mapa",
		mapexp: "Si tus datos visualizados tienen coordenadas o contienen alguna dirección, gracias a Google Maps podrás representarlas en un mapa.",
		latitude: "Latitud:",
		longitude: "Longitud:",
		showMap: "Mostrar Mapa",
		twitter: "Twitter",
		twitterexp: "Descubre lo qué se está hablando en Twitter sobre el campo de tus datos que tu elijas. Aprovecha las redes sociales para sacar más partido si cabe a tus datos.",
		showTwitter: "Mostrar Twitter",
		activefilters: "Filtros activos",
		nodata: "No hay datos",
		errorroute: "Ruta incorrecta",
		errorroute1: "Rutas válidas:",
		errorcore: "Se ha producido un error",
		errorcore1: "Ese Core no existe",
		corecaption: "Selecciona un Core",
		accept: "Aceptar",
		errorcore2: "Debes especificar un Core",
		errorserverurl: "Se ha producido un error",
		errorserverurl1: "Debes especificar la URL del servidor",
		tutoh1: "¡Bienvenido!",
		tuto1: "SEFARAD te ofrece muchas posibilidades. Ponte cómodo y sigue este pequeño tour para sacar el máximo provecho a la herramienta.",
		tutoh2: "Configuración",
		tuto2: "Desde este desplegable podrás personalizar la página: título, logo, hoja de estilo... Además de otros parámetros útiles como el autocompletado de la barra de búsqueda.",
		tutoh3: "Tus resultados personalizados",
		tuto3: "El widget más importante es completamente personalizable. ¡Elige qué campos son los que quieres visualizar en todo momento!",
		tutoh4: "Más y más widgets",
		tuto4: "Añade gráficos personalizables, widgets para poder filtrar los campos que tú quieras, un mapa o el magnífico plugin de Twitter.",
		tutoh5: "Búsqueda textual",
		tuto5: "Realiza todas las búsquedas textuales que quieras. Disfruta del autocompletado y, si eres un usuario experto, prueba con consultas SPARQL.",
		tutoh6: "¡Y guarda los cambios!",
		tuto6: "Cuando realices cambios en los Widgets o en la configuración, ¡no te olvides de guardarlos!",
		tutoh7: "Créditos",
		tuto7: "Este proyecto se ha realizado en el GSI (Grupo de Sistemas Inteligentes) de la UPM (Universidad Politécnica de Madrid)",
		
		promoheader: "Descubre todas las posibilidades",
		demo1a: "Demo: capitales Europeas",
		demo1b: "Nivel: básico",
		demo1c: "Explora todas las posibilidades que SEFARAD de ofrece",
		demo1d: "Widgets totalmente configurables",
		demo1e: "Internamente, se realiza una consulta sparql a la dbpedia",
		demo1f: "Ver demo",
		demo2a: "Explora tus propias consultas",
		demo2b: "Nivel: medio",
		demo2c: "Haz consultas SPARQL al punto de acceso deseado",
		demo2d: "Sin necesidad de programar una sola línea de código",
		demo2e: "¡Quiero probarlo ya!",
		demo3a: "LMF + SEFARAD = Lo + completo",
		demo3b: "Nivel: avanzado",
		demo3c: "Requiere LMF",
		demo3d: "Y configurar un Core",
		demo3e: "Opción ideal para grandes colecciones de datos",
		demo3f: "Más información",
		
		faq1a: "1. Instala LMF",
		faq1b: "LMF es un Framework que permite la configuración de un servidor avanzado, dando soporte a diferentes tecnologías Semánticas.",
		faq1c: "Dirígete a la Web oficial de LMF y descarga e instala LMF.",
		faq2a: "2. Importa tus datos",
		faq2b: "Introduce tus datos semánticos en la Base de Datos de LMF.",
		faq3a: "3. Haz consultas SPARQL",
		faq3b: "Una vez importados con éxito, ya puedes hacer consultas SPARQL desde SEFARAD.",
		faq3c: "",
		faq3d: "Si las consultas SPARQL resultan pesadas y quieres manejar grandes cantidades de datos, utiliza el siguiente módulo.",
		faq4a: "4. Configura un Core",
		faq4b: "Indexa los parámetros que quieras haciendo uso del lenguaje LDPath: http://code.google.com/p/ldpath/",
		faq4c: "",
		faq5a: "5. Usa SEFARAD",
		faq5b: "Dirígete a la siguiente ruta: sefarad.html#/main",
		faq5c: "¡Disfruta de la visualización!",
		
		gauge: "Gauge",
		gaugeexp: "Visualiza el número de resultados",
		resultstats: "Estadísticas de los Resultados",
		resultstatsexp: "Proporción",
		deleteAllFilters: "Borrar todos los filtros",
		panelbar: "Lista de Etiquetas (vertical)",
		panelbarexp: "Lista todos los valores según el campo deseado y aplica filtros individuales o múltiples.",
		piechart: "Gráfico tipo tarta",
		piechartexp: "Representa el campo deseado en un gráfico tipo tarta",
		barchart: "Gráfico de barras",
		barchartexp: "Representa el campo deseado en un gráfico de barras",
		linechart: "Gráfico lineal",
		barchartexp: "Representa el campo linealmente",
		sgvizler: "Estadísticas",
		sgvizlerexp: "Crea gráficos con consultas SPARQL",
		alreadyAdded: "Ya añadido",
		notActiveFilters: "No hay filtros activos",
		resultsvertical: "Resultados (vertical)",
		resultsverticalexp: "",
		resultsgrid: "Resultados (grid)",
		resultsgridexp: "",
		
        },
        {
            lang: "English",
		results: "Results",
		configuration: "Configuration",
		personalization: "Personalization",
		pagetitle: "Page title",
		logo: "Page logo",
                language: "Language",
		langcaption: "Choose a language",
                autocomplete: "Autocomplete search with",
		fieldcaption: "Choose a field",
		globalvar: "Global variables",
		lmfroute: "LMF route",
		sparqlaccessendpoint: "SPARQL endpoint",
                advancedoptions: "Advanced options",
                reindexsolr: "Reindex Core",
                resetconf: "Reset Configuration",
                savechanges: "Save changes",
		openconf: "Open Configuration",
		closeconf: "Close Configuration",
		addWidget: "Add a Widget",
		addWidget2: "Add",
		tagcloud: "Tagcloud",
		tagcloudexp: "List all values of one certain field and apply all filters you want.",
		tagcloudexp2: "It's really easy to explore your data!",
		numericwidget: "Numeric filter",
		numericwidgetexp: "Use this as a range slider so you can also filter fields with numbers.",
		staticgraph: "Static graph",
		staticgraphexp: "Thanks to <a href='http://code.google.com/p/sgvizler/' target='_blank'>sgvizler</a> library, you can make SPARQL queries and visualize the result in a pie chart.",
		map: "Map",
		mapexp: "If you have geographic coordinates in your data, you can visualize them in a Map thanks to Google Maps.",
		latitude: "Latitude:",
		longitude: "Longitude:",
		showMap: "Show Map",
		twitter: "Twitter",
		twitterexp: "Select a field and see what's going on Twitter about items contained in it.",
		showTwitter: "Show Twitter Widget",
		resultstats: "Results statistics",
		activefilters: "Active filters",
		nodata: "There is no data to show",
		errorroute: "Wrong route",
		errorroute1: "Valid routes:",
		errorcore: "Ops! There was an error",
		errorcore1: "That Core doesn't exist",
		corecaption: "Choose a Core",
		accept: "Accept",
		errorcore2: "You must specify one Core",
		errorserverurl: "Ops! There was an error",
		errorserverurl1: "You must setup server URL",
		tutoh1: "Welcome!",
		tuto1: "SEFARAD offers you many possibilities. Sit back and follow this small tour to get the most out of the tool.",
		tutoh2: "Configuration",
		tuto2: "Desde este desplegable podrás personalizar la página: título, logo, hoja de estilo... Además de otros parámetros útiles como el autocompletado de la barra de búsqueda.",
		tutoh3: "Tus resultados personalizados",
		tuto3: "El widget más importante es completamente personalizable. ¡Elige qué campos son los que quieres visualizar en todo momento!",
		tutoh4: "Más y más widgets",
		tuto4: "Añade gráficos personalizables, widgets para poder filtrar los campos que tú quieras, un mapa o el magnífico plugin de Twitter.",
		tutoh5: "Búsqueda textual",
		tuto5: "Realiza todas las búsquedas textuales que quieras. Disfruta del autocompletado y, si eres un usuario experto, prueba con consultas SPARQL.",
		tutoh6: "¡Y guarda los cambios!",
		tuto6: "Cuando realices cambios en los Widgets o en la configuración, ¡no te olvides de guardarlos!",
		tutoh7: "Créditos",
		tuto7: "Este proyecto se ha realizado en el GSI (Grupo de Sistemas Inteligentes) de la UPM (Universidad Politécnica de Madrid)",
		
		promoheader: "Discover all possibilities",
		demo1a: "Demo: European capitals",
		demo1b: "Level: basic",
		demo1c: "Learn all possibilities SEFARAD provides you",
		demo1d: "Customizable Widgets",
		demo1e: "It works with a sparql query to dbpedia",
		demo1f: "Go to demo",
		demo2a: "Explore your own queries",
		demo2b: "Level: medium",
		demo2c: "Make SPARQL queries to the endpoint you choose",
		demo2d: "No extra source code needed! Everything is on the user interface.",
		demo2e: "I want to try it now!",
		demo3a: "LMF + SEFARAD = The most complete",
		demo3b: "Level: advanced",
		demo3c: "LMF required",
		demo3d: "You also need to create a Core",
		demo3e: "Ideal option for huge collections of data",
		demo3f: "More information",
		
		faq1a: "Test",
        },

    ];
